TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstFeature.urls')),
    path('', include('greenFeature.urls',namespace='greenFeature')),
    path('', include('purpleFeature.urls',namespace='purpleFeature')),
    path('', include('blueFeature.urls',namespace='blueFeature')),
    path('', include('sesikonsultasi.urls',namespace='redFeature')),
]

firstFeature/urls.py
from django.urls import path
from . import views

app_name = 'firstFeature'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.loginPage, name='login_page'),
    path('register/', views.registerPage, name='register_page'),
    path('logout/', views.logout, name='logout'),
]

firstFeature/models.py
from django.db import models

firstFeature/forms.py
from django import forms
from django.forms.formsets import formset_factory
from django.forms import widgets

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "right"}), max_length=50)
    
class RegisterForm(forms.Form):
    role = forms.CharField(max_length=50, initial="admin")
    username = forms.CharField(max_length=50)
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "right"}))
    nomor_identitas = forms.CharField(max_length=50)
    nama_lengkap = forms.CharField(max_length=50)
    tanggal_lahir = forms.DateField(widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),input_formats=('%Y-%m-%d', ))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "right"}))
    alamat = forms.CharField(widget=forms.Textarea)
    nomor_SIP = forms.CharField(max_length=50)
    spesialisasi = forms.CharField(widget=forms.Textarea)
    alergi = forms.CharField(max_length=50)
    
class AlergiForm(forms.Form):
    alergi = forms.CharField(label="alergi",max_length=50)
    
AlergiFormset = formset_factory(AlergiForm, extra=1)

firstFeature/views.py
from django.db import connection, DatabaseError, transaction
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm, AlergiFormset

def homepage(request):
    if 'Username' in request.session:
        return redirect("greenFeature:profile_page")
    return render(request, 'homepage.html')
    
def loginPage(request):
    if 'Username' in request.session:
        return redirect("greenFeature:profile_page")
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            if verifyLoginValidation(username, password):
                role = getPenggunaType(username)
                request.session['Role'] = role
                request.session['Username'] = username
                return redirect('greenFeature:profile_page')
            else:
                return render(request, 'login.html', {'form':form, 'err':'data yang dimasukkan tidak terdata'})
    else :
        form = LoginForm()
    return render(request, 'login.html', {'form':form})

def registerPage(request):
    if 'Username' in request.session:
        return redirect("greenFeature:profile_page")
    if request.method == "POST":
        form = RegisterForm(request.POST)
        role = request.POST['role']
        username = request.POST['username']
        password = request.POST['password']
        nomor_identitas = request.POST['nomor_identitas']
        nama_lengkap = request.POST['nama_lengkap']
        tanggal_lahir = request.POST['tanggal_lahir']
        email = request.POST['email']
        alamat = request.POST['alamat']
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('INSERT INTO pengguna VALUES (%s, %s, %s, %s, %s, %s, %s)',[email, username, password, nama_lengkap, nomor_identitas, tanggal_lahir, alamat])
            saveRole(role, request, username)
            request.session['Role'] = role
            request.session['Username'] = username
            return redirect('greenFeature:profile_page')
        except DatabaseError as e:
            return render(request, 'register.html', {'form':form, 'err':'username, nomor_identitas, atau email sudah terdaftar'})
    else :
        form = RegisterForm()
    return render(request, 'register.html', {'form':form})

def logout(request):
    request.session.flush()
    return redirect("firstFeature:homepage")

def saveRole(role, request, username):
    with transaction.atomic():
        with connection.cursor() as cursor:
            if role == "admin":
                pk = generateNomorPegawai()
                cursor.execute('INSERT INTO administrator VALUES (%s, %s, %s)',[pk, username, "RS1"])
            elif role == "dokter":
                pk = generateIdDokter()
                nomor_SIP = request.POST['nomor_SIP']
                spesialisasi = request.POST['spesialisasi']
                cursor.execute('INSERT INTO dokter VALUES (%s, %s, %s, %s)',[pk, username, nomor_SIP, spesialisasi])
            else:
                pk = generateNRM()
                alergiList = request.POST.getlist('alergi')
                cursor.execute('INSERT INTO pasien VALUES (%s, %s, %s)',[pk, username, "Hanwha Life Indonesia"])
                for alergi in alergiList:
                    cursor.execute('INSERT INTO alergi_pasien VALUES (%s, %s)',[pk, alergi])
        
def verifyLoginValidation(username, password):
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM pengguna WHERE username = %s AND password = %s', [username, password])
        pengguna = cursor.fetchone()
        if (pengguna):
            return True
        return False

def getPenggunaType(username):
    with connection.cursor() as cursor:
        cursor.execute('SELECT username FROM dokter WHERE username = %s', [username])
        dokter = cursor.fetchone()
        if (dokter):
            return "dokter"
        cursor.execute('SELECT username FROM pasien WHERE username = %s', [username])
        pasien = cursor.fetchone()
        if (pasien):
            return "pasien"
        return "admin"
            
def generateNRM():
    with connection.cursor() as cursor:
        cursor.execute('SELECT no_rekam_medis FROM pasien ORDER BY RIGHT(no_rekam_medis, -3)::int DESC LIMIT 1')
        pasien = cursor.fetchone()
        if(pasien):
            nrm = pasien[0]
            new_number = int(nrm[3::])+1
            return "NRM"+str(new_number)
        return "NRM1"
        
def generateIdDokter():
    with connection.cursor() as cursor:
        cursor.execute('SELECT id_dokter FROM dokter ORDER BY RIGHT(id_dokter, -2)::int DESC LIMIT 1')
        dokter = cursor.fetchone()
        if(dokter):
            id_dokter = dokter[0]
            new_number = int(id_dokter[2::])+1
            return "DK"+str(new_number)
        return "DK1"
        
def generateNomorPegawai():
    with connection.cursor() as cursor:
        cursor.execute('SELECT nomor_pegawai FROM administrator ORDER BY RIGHT(nomor_pegawai, -2)::int DESC LIMIT 1')
        admin = cursor.fetchone()
        if(admin):
            nomor_pegawai = admin[0]
            new_number = int(nomor_pegawai[2::])+1
            return "AD"+str(new_number)
        return "AD1"

firstFeature/templates/homepage.html
<!DOCTYPE html>
{% load static %}
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-edge">
		<title>homepage</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/homepage.css' %}">
	</head>
	<body>
		<div class="navbar">
			<img class="logo" src="{% static 'images/LOGO.svg' %}" alt="logo">
			<a href= "{% url 'firstFeature:login_page' %}" class="login">Login</a>
			<a href= "{% url 'firstFeature:register_page' %}" class="register">Register</a>
		</div>
		<img class="gambar" style="width: 800px; margin-top: 120px; margin-left:-50px;  " src="{% static 'images/3740.jpg' %}">
		<h2 style="margin-left: 700px; font-size: 30px; font-family: open sans; font-weight:lighter; margin-top:-300px; color: #3750B2; ">Health on the go
		</h2>
		<h2 style="margin-left: 700px; font-size: 30px; font-family: open sans; font-weight: bold; margin-top:-100px; color: #3750B2; ">Medika-go,
		</h2>
		
	</body>
</html>

firstFeature/templates/login.html
<!DOCTYPE html>
{% load static %}
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-edge">
		<title>Login</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/login.css' %}">
		{% if err %}
			<script>
				alert("{{err}}");
			</script>
		{% endif %}
	</head>
	<body>
		<div class="rectangle"></div>
		<img class="logo" src="{% static 'images/LOGO.svg' %}" alt="logo">
		<form method="POST" action="">
				{% csrf_token %}
				<p class="username">username</p> {{ form.username }}
				<p class="password">password</p> {{ form.password }}
			<button type="submit" class="login">Login</button>
		</form>
		<a href="#" class="forgot_password">forgot password?</a>
	</body>
</html>

firstFeature/templates/register.html
<!DOCTYPE html>
{% load static %}
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-edge">
		<title>Register</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/register.css' %}">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
		<script type="text/javascript" src="{% static 'javascript/register.js' %}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
		{% if err %}
			<script>
				alert("{{err}}");
			</script>
		{% endif %}
	</head>
	<body id="body_buat_tindakan">
		<div id="box">
			<br>
			<br>
			<img class="logo" src="{% static 'images/LOGO.svg' %}" alt="logo">
			<br>
			<br>
			<form class="needs-validation" method="POST" novalidate>
				{% csrf_token %}
				<input type="text" name="role" id="role_clicked" style="display:none;position:absolute;" value="admin">
				<div class="form-row">
					<label class="col-sm-5 col-form-label">role</label>
					<div class="form-group col-md-2">
						<button type="button" class="button_clicked" id="admin">admin</button>
					</div>
					<div class="form-group col-md-2">
						<button type="button" class="button_unclicked" id="dokter">dokter</button>
					</div>
					<div class="form-group col-md-2">
						<button type="button" class="button_unclicked" id="pasien">pasien</button>
					</div>
				</div>
				
				<div class="form-row">
					<label class="col-sm-4 col-form-label">username</label>
					<div class="form-group col-sm-8">
						<input type="text" name="username" class="form-control form-control-sm input pengguna_form" placeholder="max: 50" required>
						<div class="invalid-feedback">
							Please enter a value.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row">
					<label class="col-sm-4 col-form-label">password</label>
					<div class="form-group col-sm-8">
						<input type="password" name="password" class="form-control form-control-sm input pengguna_form" required>
						<div class="invalid-feedback">
							Please enter a value.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row">
					<label class="col-sm-4 col-form-label">nomor identitas</label>
					<div class="form-group col-sm-8">
						<input type="text" name="nomor_identitas" class="form-control form-control-sm input pengguna_form" placeholder="max: 50" required>
						<div class="invalid-feedback">
							Please enter a value.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row">
					<label class="col-sm-4 col-form-label">nama lengkap</label>
					<div class="form-group col-sm-8">
						<input type="text" name="nama_lengkap" class="form-control form-control-sm input pengguna_form" placeholder="max: 50" required>
						<div class="invalid-feedback">
							Please enter a value.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row">
					<label class="col-sm-4 col-form-label">tanggal lahir</label>
					<div class="form-group col-sm-8">
						<input type="date" name="tanggal_lahir" class="form-control form-control-sm input pengguna_form" required>
						<div class="invalid-feedback">
							Please enter a value.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row">
					<label class="col-sm-4 col-form-label">email</label>
					<div class="form-group col-sm-8">
						<input type="email" name="email" class="form-control form-control-sm input pengguna_form" placeholder="max: 50" required>
						<div class="invalid-feedback">
							Please enter a valid email.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row">
					<label class="col-sm-4 col-form-label">alamat</label>
					<div class="form-group col-sm-8">
						<textarea class="form-control form-control-sm" name="alamat" rows="2" style="border: 0.208vw solid #FF7364;border-radius: 0.8vw"></textarea>
						<div class="invalid-feedback">
							Please enter a value.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row" id="nomor_SIP" style="display:none;">
					<label class="col-sm-4 col-form-label">Nomor SIP</label>
					<div class="form-group col-sm-8">
						<input type="text" name="nomor_SIP" class="form-control form-control-sm input dokter_form" placeholder="max: 50" required>
						<div class="invalid-feedback">
							Please enter a value.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row" id="spesialisasi" style="display:none;">
					<label class="col-sm-4 col-form-label">Spesialisasi</label>
					<div class="form-group col-sm-8">
						<input type="text" name="spesialisasi" class="form-control form-control-sm input dokter_form" required>
						<div class="invalid-feedback">
							Please enter a value.
						</div>
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>
				</div>
				
				<div class="form-row" id="id_tindakan" style="display:none;">
					<label for="exampleInputPassword1" class="col-sm-4 col-form-label">Alergi</label>
					<div class="form-group col-md-6">
						<input type="text" name="alergi" class="form-control form-control-sm input pasien_form" placeholder="max: 50" required>
						<div class="valid-feedback">
							Looks good!
						</div>
						<div class="invalid-feedback">
							Please enter a value. Or check if there's any duplications
						</div>
					</div>
					<div class="form-group col-md-2">
						<button type="button" class="button_plus" id="button_plus_active">+</button>
					</div>
				</div>
				
				<br>
				<button type="submit" class="button">Register</button>
			</form>
			<br>
			<br>
		</div>
		
		<script type="text/javascript" src="{% static 'javascript/register.js' %}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	</body>
</html>