TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstFeature.urls')),
    path('', include('greenFeature.urls',namespace='greenFeature')),
    path('', include('purpleFeature.urls',namespace='purpleFeature')),
    path('', include('blueFeature.urls',namespace='blueFeature')),
    path('', include('sesikonsultasi.urls',namespace='redFeature')),
]

blueFeature/urls.py
from django.urls import path
from . import views

app_name = 'blueFeature'

urlpatterns = [
    path('buatTransaksi/', views.buatTransaksi, name='buatTransaksi'),
    
    path('RUDadmin/', views.rudAdmin, name='RUDadmin'),
    
    path('updateTransaksi/<id_transaksi>', views.updateTransaksi, name='updateTransaksi'),
    path('updateTransaksi/', views.updateTransaksi, name='updateTransaksi'),

    path('deleteTransaksi/<id_transaksi>', views.deleteTransaksi, name='deleteTransaksi'),
    path('deleteTransaksi/', views.deleteTransaksi, name='deleteTransaksi'),
]

firstFeature/urls.py
from django.urls import path
from . import views

app_name = 'firstFeature'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.loginPage, name='login_page'),
    path('register/', views.registerPage, name='register_page'),
    path('logout/', views.logout, name='logout'),
]

greenFeature/urls.py
from django.urls import path
from . import views

app_name = 'greenFeature'
urlpatterns = [
    path('profile/', views.profilePage, name='profile_page'),
    
    path('buat-tindakan/', views.buatTindakanPage, name='buat_tindakan'),
    
    path('daftar-tindakan/', views.daftarTindakanPage, name='daftar_tindakan'),
    
    path('update-tindakan/<id_konsultasi>/<no_urut>', views.updateTindakanPage, name='update_tindakan'),
    path('update-tindakan/', views.updateTindakanPage, name='update_tindakan'),
    
    path('buat-tindakan-poliklinik/', views.buatTindakanPoliklinikPage, name='buat_tindakan_poliklinik'),
    
    path('daftar-tindakan-poliklinik/', views.daftarTindakanPoliklinikPage, name='daftar_tindakan_poliklinik'),
    
    path('update-tindakan-poliklinik/<id_tindakan_poli>', views.updateTindakanPoliklinikPage, name='update_tindakan_poliklinik'),
    path('update-tindakan-poliklinik/', views.updateTindakanPoliklinikPage, name='update_tindakan_poliklinik'),
    
    path('delete-tindakan-poliklinik/<id_tindakan_poli>', views.deleteTindakanPoliklinikPage, name='delete_tindakan_poliklinik'),
    path('delete-tindakan-poliklinik/', views.deleteTindakanPoliklinikPage, name='delete_tindakan_poliklinik'),
    
    path('delete-tindakan/<id_konsultasi>/<no_urut>', views.deleteTindakanPage, name='delete_tindakan'),
    path('delete-tindakan/', views.deleteTindakanPage, name='delete_tindakan'),
]

purpleFeature/urls.py
from django.urls import path
from . import views

app_name = "purpleFeature"

urlpatterns = [
    path('daftardokter/',views.daftardokter,name = "daftardokter"),

    path('jadwal-poliklinik/',views.jadwalpoliklinik,name="jadwalpoliklinik"),

    path('jadwal-poliklinik-details/<id_poliklinik>',views.jadwalpoliklinikdetails,name = "jadwalpoliklinikdetails"),
    path('jadwal-poliklinik-details/',views.jadwalpoliklinikdetails,name = "jadwalpoliklinikdetails"),

    path('pembuatan-layanan-poliklinik/',views.buatlayananpoliklinik,name = "buatlayananpoliklinik"),

    path('update-daftar-dokter/<id_dokter>/<kode_rs>',views.updatedaftardokter,name = "updatedaftardokter"),
    path('update-daftar-dokter/',views.updatedaftardokter,name="updatedaftardokter"),

    path('daftar-dokter-rs-cabang/',views.daftardoktercabang,name = "daftardoktercabang"),

    path('update-layanan-poliklinik/<id_poliklinik>/<kode_rs>',views.updatelayananpoliklinik,name = "updatelayananpoliklinik"),
    path('update-layanan-poliklinik/',views.updatelayananpoliklinik,name = "updatelayananpoliklinik"),

    path('update-jadwal-poliklinik/<id_jadwal_layanan_poliklinik>',views.updatejadwalpoliklinik,name = "updatejadwalpoliklinik"),
    path('update-jadwal-poliklinik/',views.updatejadwalpoliklinik,name = "updatejadwalpoliklinik"),

    path('delete-layanan-poliklinik/<id_poliklinik>/<kode_rs>',views.deletelayananpoliklinik,name="deletelayananpoliklinik"),
    path('delete-layanan-poliklinik',views.deletelayananpoliklinik,name="deletelayananpoliklinik"),

    path('delete-jadwal-poliklinik/<id_poliklinik>/<id_layanan>',views.deletejadwalpoliklinik,name="deletejadwalpoliklinik"),
    path('delete-jadwal-poliklinik/',views.deletejadwalpoliklinik,name="deletejadwalpoliklinik"),

    path('delete-dokter/<id_dokter>/<kode_rs>',views.deletedokter,name="deletedokter"),
    path('delete-dokter/',views.deletedokter,name="deletedokter")
]

sesikonsultasi/urls.py
from django.urls import path
from . import views

app_name = 'sesikonsultasi'

urlpatterns = [
    path('buat-sesikonsultasi/', views.buatSesiPage, name='buat_sesikonsultasi'),

    path('daftar-sesikonsultasi/', views.daftarSesiPage, name='daftar_sesikonsultasi'),

    path('update-sesikonsultasi/<id_konsultasi>/<no_rekam_medis>/', views.updateSesiPage, name='update_sesikonsultasi'),
    path('update-sesikonsultasi/', views.updateSesiPage, name='update_sesikonsultasi'),

    path('buat-rscabang/', views.buatRscabangPage, name='buat_rscabang'),

    path('daftar-rscabang/', views.daftarRscabangPage, name='daftar_rscabang'),
    
    path('update-rscabang/<kode_rs>', views.updateRscabangPage, name='update_rscabang'),
    path('update-rscabang/', views.updateRscabangPage, name='update_rscabang'),

    path('delete-sesikonsultasi/<id_konsultasi>/<no_rekam_medis>', views.deleteSesiPage, name='delete_sesikonsultasi'),
    path('delete-sesikonsultasi/', views.deleteSesiPage, name='delete_sesikonsultasi'),

    path('delete-rscabang/<kode_rs>', views.deleteRscabangPage, name='delete_rscabang'),
    path('delete-rscabang/', views.deleteRscabangPage, name='delete_rscabang'),
    # dilanjutkan ...
]

greenFeature/models.py
from django.db import models

# Create your models here.

greenFeature/views.py
from django.db import connection, DatabaseError, transaction
from django.shortcuts import render, redirect, reverse

def profilePage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        alergi = ""
        cursor.execute('SELECT * FROM pengguna WHERE username = %s',[username])
        user = cursor.fetchone()
        user_role = getUserBasedOnRole(role, username)
        if(role == "pasien"):
            cursor.execute("SELECT pasien.no_rekam_medis, STRING_AGG(alergi_pasien.alergi,', ') FROM pasien INNER JOIN alergi_pasien ON pasien.no_rekam_medis = alergi_pasien.no_rekam_medis WHERE pasien.no_rekam_medis = %s GROUP BY pasien.no_rekam_medis", [user_role[0]])
            alergi_pasien = cursor.fetchone()
            alergi = alergi_pasien[1]
    return render(request, 'profile_'+role+".html", {'role':role,'user':user,'user_role':user_role,'alergi':alergi})
    
def buatTindakanPage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        cursor.execute('SELECT id_konsultasi FROM sesi_konsultasi ORDER BY RIGHT(id_konsultasi, -2)::int')
        id_konsultasis = cursor.fetchall()
        cursor.execute('SELECT id_transaksi FROM transaksi ORDER BY RIGHT(id_transaksi, -2)::int')
        id_transaksis = cursor.fetchall()
        cursor.execute('SELECT id_tindakan_poli FROM tindakan_poli ORDER BY RIGHT(id_tindakan_poli, -2)::int')
        id_tindakan_polis = cursor.fetchall()
    if request.method == 'POST':
        id_konsultasi = request.POST["id_konsultasi"]
        id_transaksi = request.POST["id_transaksi"]
        catatan = request.POST["catatan"]
        id_tindakan_list = request.POST.getlist("id_tindakan_form")
        nomor_urut = generateNomorUrut(id_konsultasi)
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('INSERT INTO tindakan VALUES (%s, %s, %s, %s, %s)', [id_konsultasi, nomor_urut, 0, catatan, id_transaksi])
                    for id_tindakan_poli in id_tindakan_list:
                        cursor.execute('INSERT INTO daftar_tindakan VALUES (%s, %s, %s)', [id_konsultasi, nomor_urut, id_tindakan_poli])
            return redirect('greenFeature:daftar_tindakan')
        except DatabaseError as e:
            return render(request, "buat_tindakan.html", {'id_konsultasis':id_konsultasis, 'id_transaksis':id_transaksis, 'id_tindakan_polis':id_tindakan_polis, 'err':'terdapat error ketika ingin membuat tindakan, mohon dicoba lagi'})
    else:
        if(role == "admin"):
            return render(request, "buat_tindakan.html", {'id_konsultasis':id_konsultasis, 'id_transaksis':id_transaksis, 'id_tindakan_polis':id_tindakan_polis})
        else:
            return redirect('greenFeature:profile_page')
        
def daftarTindakanPage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        daftar_tindakan_poli = []
        cursor.execute('SELECT * FROM tindakan')
        tindakans = cursor.fetchall()
        for tindakan in tindakans:
            cursor.execute('SELECT id_tindakan_poli FROM daftar_tindakan WHERE id_konsultasi = %s AND no_urut = %s', [tindakan[0], tindakan[1]])
            id_tindakan_polis = cursor.fetchall()
            tindakan_poli = [id_tindakan_poli[0] for id_tindakan_poli in id_tindakan_polis]
            daftar_tindakan_poli.append(tindakan_poli)
    mylist = zip(daftar_tindakan_poli, tindakans)
    if(role == "admin"):
        return render(request, "daftar_tindakan.html", {'mylist':mylist})
    else:
        return render(request, "daftar_tindakan_non_admin.html", {'mylist':mylist})
        
def updateTindakanPage(request, id_konsultasi, no_urut):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM tindakan WHERE id_konsultasi = %s AND no_urut = %s',[id_konsultasi, no_urut])
        tindakan = cursor.fetchone()
        cursor.execute('SELECT id_tindakan_poli FROM daftar_tindakan WHERE id_konsultasi = %s AND no_urut = %s', [id_konsultasi, no_urut])
        id_tindakan_polis = cursor.fetchall()
    if request.method == 'POST':
        catatan = request.POST["catatan"]
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('UPDATE tindakan SET catatan = %s WHERE id_konsultasi = %s AND no_urut = %s', [catatan, id_konsultasi, no_urut])
            return redirect('greenFeature:daftar_tindakan')
        except DatabaseError as e:
            return render(request, "update_tindakan.html", {'tindakan':tindakan, 'id_tindakan_polis':id_tindakan_polis, 'err':'terdapat error ketika ingin update tindakan, mohon dicoba lagi, atau kembali ke daftar tindakan'})
    else:
        if(role == "admin" and tindakan):
            return render(request, "update_tindakan.html", {'tindakan':tindakan, 'id_tindakan_polis':id_tindakan_polis})
        else:
            return redirect('greenFeature:profile_page')

def deleteTindakanPage(request, id_konsultasi, no_urut):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    if(role == "admin"):
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('DELETE FROM tindakan WHERE id_konsultasi = %s AND no_urut = %s',[id_konsultasi, no_urut])
        except DatabaseError as e:
            return redirect('greenFeature:daftar_tindakan')
    return redirect('greenFeature:daftar_tindakan')
            
def buatTindakanPoliklinikPage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        cursor.execute('SELECT id_poliklinik FROM layanan_poliklinik ORDER BY RIGHT(id_poliklinik, -2)::int')
        id_polikliniks = cursor.fetchall()
    if request.method == 'POST':
        id_poliklinik = request.POST["id_poliklinik"]
        nama_tindakan = request.POST["nama_tindakan"]
        deskripsi = request.POST["deskripsi"]
        tarif = request.POST["tarif"]
        pk = generateIdTindakanPoli()
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('INSERT INTO tindakan_poli VALUES (%s, %s, %s, %s, %s)', [pk, id_poliklinik, nama_tindakan, int(tarif), deskripsi])
            return redirect('greenFeature:daftar_tindakan_poliklinik')
        except DatabaseError as e:
            return render(request, "buat_tindakan_poliklinik.html", {'id_polikliniks':id_polikliniks, 'err':'terdapat error ketika ingin membuat tindakan poliklinik, mohon dicoba lagi'})
    else:
        if(role == "admin"):
            return render(request, "buat_tindakan_poliklinik.html", {'id_polikliniks':id_polikliniks})
        else:
            return redirect('greenFeature:profile_page')

def daftarTindakanPoliklinikPage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM tindakan_poli ORDER BY RIGHT(id_tindakan_poli, -2)::int')
        tindakan_polis = cursor.fetchall()
    if(role == "admin"):
        return render(request, "daftar_tindakan_poliklinik.html", {'tindakan_polis':tindakan_polis})
    else:
        return render(request, "daftar_tindakan_poliklinik_non_admin.html", {'tindakan_polis':tindakan_polis})

def updateTindakanPoliklinikPage(request, id_tindakan_poli):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM tindakan_poli WHERE id_tindakan_poli = %s',[id_tindakan_poli])
        tindakan_poli = cursor.fetchone()
        cursor.execute('SELECT id_poliklinik FROM layanan_poliklinik ORDER BY RIGHT(id_poliklinik, -2)::int')
        id_polikliniks = cursor.fetchall()
    if request.method == 'POST':
        id_poliklinik = request.POST["id_poliklinik"]
        nama_tindakan = request.POST["nama_tindakan"]
        deskripsi = request.POST["deskripsi"]
        tarif = request.POST["tarif"]
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('UPDATE tindakan_poli SET id_poliklinik = %s, nama_tindakan = %s, tarif = %s, deskripsi = %s WHERE id_tindakan_poli = %s', [id_poliklinik, nama_tindakan, int(tarif), deskripsi, id_tindakan_poli])
            return redirect('greenFeature:daftar_tindakan_poliklinik')
        except DatabaseError as e:
            return render(request, "update_tindakan_poliklinik.html", {'tindakan_poli':tindakan_poli, 'id_polikliniks':id_polikliniks, 'err':'terdapat error ketika ingin update tindakan poliklinik, mohon dicoba lagi atau kembali ke daftar tindakan poliklinik'})
    else:

greenFeature/templates/daftar_tindakan.html
<!DOCTYPE html>
{% load static %}
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-edge">
		<title>Daftar Tindakan</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/daftar_tindakan_poliklinik.css' %}">
		<script type="text/javascript" src="{% static 'javascript/daftar_tindakan.js' %}"></script>
		<script type="text/javascript" src="{% static 'javascript/navbar.js' %}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"></link>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
		{% if err %}
			<script>
				alert("{{err}}");
			</script>
		{% endif %}
	</head>
	<body id="body_buat_tindakan">
		{% include 'navbar.html' %}
		<h3 id="formtitle">Daftar Tindakan</h3>
		<div id="box">
			<table class="table table-borderless" style="margin-left:20px;">
			  <thead>
			  
				<tr style="color:#FF7364;">
				  <th scope="col" style="padding-top:1.5rem !important;">ID Konsultasi</th>
				  <th scope="col" style="padding-top:1.5rem !important;">No Urut</th>
				  <th scope="col" style="padding-top:1.5rem !important;">Biaya</th>
				  <th scope="col" style="padding-top:1.5rem !important;width:150px;">Catatan</th>
				  <th scope="col" style="padding-top:1.5rem !important;">ID Transaksi</th>
				  <th scope="col" style="padding-top:1.5rem !important;display:inline-block;">ID Tindakan Poliklinik</th>
				  <th scope="col" style="padding-top:1.5rem !important;"></th>
				</tr>
			  </thead>
			  <tbody>
				{% for daftar_tindakan_poli, tindakan in mylist %}
				<tr>
				  <th scope="row">{{tindakan.0}}</th>
				  <td>{{tindakan.1}}</td>
				  <td>{{tindakan.2}}</td>
				  <td>{{tindakan.3}}</td>
				  <td>{{tindakan.4}}</td>
				  <td>
					{% for id_tindakan_poli in daftar_tindakan_poli %}
						<li>{{id_tindakan_poli}}</li>
					{% endfor %}
				  </td>
				  <td>
					<button type="submit" class="button_update" scope="col"><a style = "text-decoration:none;" href="{% url 'greenFeature:update_tindakan' %}{{tindakan.0}}/{{tindakan.1}}">Update</a></button>
					<button type="submit" class="button_delete" scope="col"><a style = "text-decoration:none;color:#FFFFFF;" href="{% url 'greenFeature:delete_tindakan' %}{{tindakan.0}}/{{tindakan.1}}">Delete</a></button>
				  </td>
				</tr>
				{% endfor %}
			  </tbody>
			</table>
		</div>
		
		<script type="text/javascript" src="{% static 'javascript/daftar_tindakan.js' %}"></script>
		<script type="text/javascript" src="{% static 'javascript/navbar.js' %}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	</body>
</html>

greenFeature/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"></link>
    <script type="text/javascript" src="{% static 'javascript/navbar.js' %}"></script>
</head>
	<body>
		<nav class="navbar navbar-expand-md navbar-light" style="background-color: #F3F9FF;height:17vh;">
			<a class="navbar-brand" href="{% url 'greenFeature:profile_page' %}"><img class="logo" src="{% static 'images/LOGO.svg' %}"></img></a>
			
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto"">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Sesi Konsultasi
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
							<a class="dropdown-item" href="{% url 'redFeature:buat_sesikonsultasi' %}">Buat Sesi Konsultasi</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'redFeature:daftar_sesikonsultasi' %}">Daftar Sesi Konsultasi</a>
						</div>
					</li>
					
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" style="color:#000000;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Poliklinik
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
							<a class="dropdown-item" href="{% url 'purpleFeature:buatlayananpoliklinik' %}">Buat Layanan Poliklinik</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'purpleFeature:jadwalpoliklinik' %}">Daftar Layanan Poliklinik</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'purpleFeature:buatlayananpoliklinik' %}">Buat Jadwal Poliklinik</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'purpleFeature:jadwalpoliklinik' %}">Daftar Jadwal Poliklinik</a>
						</div>
					</li>
					
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							RS Cabang
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
							<a class="dropdown-item" href="{% url 'redFeature:buat_rscabang' %}">Buat RS Cabang</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'redFeature:daftar_rscabang' %}">Daftar RS Cabang</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'purpleFeature:daftardoktercabang' %}">Daftarkan Dokter</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'purpleFeature:daftardokter' %}">Daftar Dokter RS Cabang</a>
						</div>
					</li>
					
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" style="color:#000000;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Tindakan
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
							<a class="dropdown-item" href="{% url 'greenFeature:buat_tindakan' %}">Buat Tindakan</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'greenFeature:daftar_tindakan' %}">Daftar Tindakan</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'greenFeature:buat_tindakan_poliklinik' %}">Buat Tindakan Poliklinik</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'greenFeature:daftar_tindakan_poliklinik' %}">Daftar Tindakan Poliklinik</a>
						</div>
					</li>
					
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Resep & Obat 
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
							<a class="dropdown-item" href="#">Buat Resep</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Daftar Resep</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Buat Obat</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Daftar Obat</a>
						</div>
					</li>
					
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Transaksi 
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
							<a class="dropdown-item" href="{% url 'blueFeature:buatTransaksi'%}">Buat Transaksi</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'blueFeature:RUDadmin'%}">Daftar Transaksi</a>
						</div>
					</li>
					
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<img src="{% static 'images/profile_icon.svg' %}" class="profile_icon"></img>
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
							<a class="dropdown-item" href="{% url 'greenFeature:profile_page' %}">Profil</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'firstFeature:logout' %}">Log out</a>
						</div>
					</li>
					
				</ul>
			</div>
		</nav>
		<script type="text/javascript" src="{% static 'javascript/navbar.js' %}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	</body>
</html>