TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstFeature.urls')),
    path('', include('greenFeature.urls',namespace='greenFeature')),
    path('', include('purpleFeature.urls',namespace='purpleFeature')),
    path('', include('blueFeature.urls',namespace='blueFeature')),
    path('', include('sesikonsultasi.urls',namespace='redFeature')),
]

blueFeature/urls.py
from django.urls import path
from . import views

app_name = 'blueFeature'

urlpatterns = [
    path('buatTransaksi/', views.buatTransaksi, name='buatTransaksi'),
    
    path('RUDadmin/', views.rudAdmin, name='RUDadmin'),
    
    path('updateTransaksi/<id_transaksi>', views.updateTransaksi, name='updateTransaksi'),
    path('updateTransaksi/', views.updateTransaksi, name='updateTransaksi'),

    path('deleteTransaksi/<id_transaksi>', views.deleteTransaksi, name='deleteTransaksi'),
    path('deleteTransaksi/', views.deleteTransaksi, name='deleteTransaksi'),
]

firstFeature/urls.py
from django.urls import path
from . import views

app_name = 'firstFeature'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.loginPage, name='login_page'),
    path('register/', views.registerPage, name='register_page'),
    path('logout/', views.logout, name='logout'),
]

greenFeature/urls.py
from django.urls import path
from . import views

app_name = 'greenFeature'
urlpatterns = [
    path('profile/', views.profilePage, name='profile_page'),
    
    path('buat-tindakan/', views.buatTindakanPage, name='buat_tindakan'),
    
    path('daftar-tindakan/', views.daftarTindakanPage, name='daftar_tindakan'),
    
    path('update-tindakan/<id_konsultasi>/<no_urut>', views.updateTindakanPage, name='update_tindakan'),
    path('update-tindakan/', views.updateTindakanPage, name='update_tindakan'),
    
    path('buat-tindakan-poliklinik/', views.buatTindakanPoliklinikPage, name='buat_tindakan_poliklinik'),
    
    path('daftar-tindakan-poliklinik/', views.daftarTindakanPoliklinikPage, name='daftar_tindakan_poliklinik'),
    
    path('update-tindakan-poliklinik/<id_tindakan_poli>', views.updateTindakanPoliklinikPage, name='update_tindakan_poliklinik'),
    path('update-tindakan-poliklinik/', views.updateTindakanPoliklinikPage, name='update_tindakan_poliklinik'),
    
    path('delete-tindakan-poliklinik/<id_tindakan_poli>', views.deleteTindakanPoliklinikPage, name='delete_tindakan_poliklinik'),
    path('delete-tindakan-poliklinik/', views.deleteTindakanPoliklinikPage, name='delete_tindakan_poliklinik'),
    
    path('delete-tindakan/<id_konsultasi>/<no_urut>', views.deleteTindakanPage, name='delete_tindakan'),
    path('delete-tindakan/', views.deleteTindakanPage, name='delete_tindakan'),
]

purpleFeature/urls.py
from django.urls import path
from . import views

app_name = "purpleFeature"

urlpatterns = [
    path('daftardokter/',views.daftardokter,name = "daftardokter"),

    path('jadwal-poliklinik/',views.jadwalpoliklinik,name="jadwalpoliklinik"),

    path('jadwal-poliklinik-details/<id_poliklinik>',views.jadwalpoliklinikdetails,name = "jadwalpoliklinikdetails"),
    path('jadwal-poliklinik-details/',views.jadwalpoliklinikdetails,name = "jadwalpoliklinikdetails"),

    path('pembuatan-layanan-poliklinik/',views.buatlayananpoliklinik,name = "buatlayananpoliklinik"),

    path('update-daftar-dokter/<id_dokter>/<kode_rs>',views.updatedaftardokter,name = "updatedaftardokter"),
    path('update-daftar-dokter/',views.updatedaftardokter,name="updatedaftardokter"),

    path('daftar-dokter-rs-cabang/',views.daftardoktercabang,name = "daftardoktercabang"),

    path('update-layanan-poliklinik/<id_poliklinik>/<kode_rs>',views.updatelayananpoliklinik,name = "updatelayananpoliklinik"),
    path('update-layanan-poliklinik/',views.updatelayananpoliklinik,name = "updatelayananpoliklinik"),

    path('update-jadwal-poliklinik/<id_jadwal_layanan_poliklinik>',views.updatejadwalpoliklinik,name = "updatejadwalpoliklinik"),
    path('update-jadwal-poliklinik/',views.updatejadwalpoliklinik,name = "updatejadwalpoliklinik"),

    path('delete-layanan-poliklinik/<id_poliklinik>/<kode_rs>',views.deletelayananpoliklinik,name="deletelayananpoliklinik"),
    path('delete-layanan-poliklinik',views.deletelayananpoliklinik,name="deletelayananpoliklinik"),

    path('delete-jadwal-poliklinik/<id_poliklinik>/<id_layanan>',views.deletejadwalpoliklinik,name="deletejadwalpoliklinik"),
    path('delete-jadwal-poliklinik/',views.deletejadwalpoliklinik,name="deletejadwalpoliklinik"),

    path('delete-dokter/<id_dokter>/<kode_rs>',views.deletedokter,name="deletedokter"),
    path('delete-dokter/',views.deletedokter,name="deletedokter")
]

sesikonsultasi/urls.py
from django.urls import path
from . import views

app_name = 'sesikonsultasi'

urlpatterns = [
    path('buat-sesikonsultasi/', views.buatSesiPage, name='buat_sesikonsultasi'),

    path('daftar-sesikonsultasi/', views.daftarSesiPage, name='daftar_sesikonsultasi'),

    path('update-sesikonsultasi/<id_konsultasi>/<no_rekam_medis>/', views.updateSesiPage, name='update_sesikonsultasi'),
    path('update-sesikonsultasi/', views.updateSesiPage, name='update_sesikonsultasi'),

    path('buat-rscabang/', views.buatRscabangPage, name='buat_rscabang'),

    path('daftar-rscabang/', views.daftarRscabangPage, name='daftar_rscabang'),
    
    path('update-rscabang/<kode_rs>', views.updateRscabangPage, name='update_rscabang'),
    path('update-rscabang/', views.updateRscabangPage, name='update_rscabang'),

    path('delete-sesikonsultasi/<id_konsultasi>/<no_rekam_medis>', views.deleteSesiPage, name='delete_sesikonsultasi'),
    path('delete-sesikonsultasi/', views.deleteSesiPage, name='delete_sesikonsultasi'),

    path('delete-rscabang/<kode_rs>', views.deleteRscabangPage, name='delete_rscabang'),
    path('delete-rscabang/', views.deleteRscabangPage, name='delete_rscabang'),
    # dilanjutkan ...
]

purpleFeature/models.py
from django.db import models

# Create your models here.

purpleFeature/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import connection, DatabaseError, transaction
from django.views.generic import CreateView
from .views import *
from firstFeature.views import *

# Create your views here.
def daftardokter(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    cursor = connection.cursor()
    cursor.execute("SELECT RS.kode_rs, ARRAY_AGG(D.id_dokter) as doctors FROM dokter_rs_cabang as RS LEFT JOIN dokter as D ON D.id_dokter = RS.id_dokter WHERE D.id_dokter = RS.id_dokter GROUP BY RS.kode_rs ORDER BY RS.kode_rs;"),
    arguements = {
        'doctors': cursor.fetchall()
    }
    if(role == 'admin'):
        return render(request,"DaftarDokterAdmin.html",arguements)
    else:
        return render(request,"DaftarDokter.html",arguements)


def jadwalpoliklinik(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    cursor = connection.cursor()
    
    cursor.execute("SELECT * from layanan_poliklinik;")
    objects = cursor.fetchall()
    args = {
        'services':objects
    }
    if(role == 'admin'):
        return render(request,"JadwalPoliklinikAdmin.html",args)
    else:
        return render(request,"JadwalPoliklinik.html",args)


def jadwalpoliklinikdetails(request,id_poliklinik):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    cursor = connection.cursor()
    
    cursor.execute("SELECT * from jadwal_layanan_poliklinik WHERE id_poliklinik=%s;",[id_poliklinik])
    objects = cursor.fetchall()
    args = {
        'schedules':objects
    }
    if(role == 'admin'):
        return render(request,"JadwalPoliklinikdetailsAdmin.html",args)
    else:
        return render(request,"JadwalPoliklinikdetails.html",args)


def buatlayananpoliklinik(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM rs_cabang ORDER BY kode_rs")
    rs = cursor.fetchall()
    cursor.execute("SELECT id_dokter FROM dokter")
    doctors=cursor.fetchall()

    if request.method == 'POST':
        cursor.execute("SELECT MAX(LENGTH(id_poliklinik)) FROM layanan_poliklinik;")
        length1=cursor.fetchone()
        cursor.execute("SELECT MAX(id_poliklinik) FROM layanan_poliklinik WHERE LENGTH(id_poliklinik)=%s",[length1])
        max = cursor.fetchone()[0][2:]
        print(max)
        newmax=str(int(max) + 1)
        newid='PL' + newmax
        nama=request.POST.get('nama')
        deskripsi=request.POST.get('deskripsi')
        kode_rs=request.POST.get('kode_rs')
        hari_list=request.POST.getlist('hari')
        waktu_mulai_list=request.POST.getlist('waktu_mulai')
        waktu_selesai_list=request.POST.getlist('waktu_selesai')
        kapasitas_list=request.POST.getlist('kapasitas')
        dokter_list=request.POST.getlist('dokter')
        with transaction.atomic():
            cursor.execute("INSERT INTO layanan_poliklinik(id_poliklinik,kode_rs_cabang,nama,deskripsi)VALUES(%s,%s,%s,%s);",[newid,kode_rs,nama,deskripsi])
        for i in range(len(hari_list)):
            with transaction.atomic():
                try:
                    cursor.execute("SELECT MAX(LENGTH(id_jadwal_poliklinik)) FROM jadwal_layanan_poliklinik")
                    length=cursor.fetchone()
                    cursor.execute("SELECT MAX(id_jadwal_poliklinik) FROM (SELECT id_jadwal_poliklinik FROM jadwal_layanan_poliklinik WHERE LENGTH(id_jadwal_poliklinik)=%s) as length;",[length])
                    maximum=cursor.fetchone()[0][3:]
                    print('maximum = '  + maximum)
                    newmaximum=str(int(maximum) + 1)
                    print(newmaximum)
                    newjpl='JPL'+newmaximum
                    cursor.execute("INSERT INTO jadwal_layanan_poliklinik(id_jadwal_poliklinik,waktu_mulai,waktu_selesai,hari,kapasitas,id_dokter,id_poliklinik) VALUES(%s,%s,%s,%s,%s,%s,%s)",[newjpl,waktu_mulai_list[i],waktu_selesai_list[i],hari_list[i],kapasitas_list[i],dokter_list[i],newid])
                    print(connection.queries)
                except DatabaseError as Error:
                    print(Error)
        return redirect("purpleFeature:jadwalpoliklinik")
    if(role == 'admin'):
        return render(request,"FormPembuatanLayananPoliklinik.html",{'rs':rs,'doctors':doctors})
    else:
        return redirect('greenFeature:profile_page')

def daftardoktercabang(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    if(role == 'admin'):
        cursor = connection.cursor()
        cursor.execute("SELECT id_dokter FROM dokter")
        doctors=cursor.fetchall()
        cursor.execute("SELECT kode_rs FROM rs_cabang")
        rs=cursor.fetchall()
        if request.method == 'POST':
            id_dokter = request.POST['id_dokter']
            kode_rs = request.POST['kode_rs']
            with transaction.atomic():
                try:
                    cursor.execute("INSERT INTO dokter_rs_cabang(id_dokter,kode_rs) VALUES(%s,%s)",[id_dokter,kode_rs])
                    return redirect("purpleFeature:daftardokter")
                    print(connection.queries)
                except DatabaseError as error:
                    print(error)
                    return redirect("purpleFeature:daftardoktercabang")
        args={
            'doctors':doctors,
            'rs':rs
        }
        return render(request,"FormDaftarDokterRsCabang.html",args)
    else:
        return redirect('greenFeature:profile_page')



def updatedaftardokter(request,id_dokter,kode_rs):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    if(role == 'admin'):
        cursor=connection.cursor()
        if request.method == 'POST':
            with transaction.atomic():
                try:
                    id_dokter1 = request.POST['id_dokter']
                    kode_rs1 = request.POST['kode_rs']
                    cursor.execute("UPDATE dokter_rs_cabang SET id_dokter=%s,kode_rs=%s WHERE id_dokter=%s AND kode_rs=%s",[id_dokter1,kode_rs1,id_dokter,kode_rs])
                    print(connection.queries)
                    return redirect("purpleFeature:daftardokter")
                except DatabaseError as error:
                    print(error)
                    return redirect("purpleFeature:daftardokter")
        cursor.execute("SELECT id_dokter,kode_rs FROM dokter_rs_cabang WHERE id_dokter=%s AND kode_rs=%s",[id_dokter,kode_rs])
        arg=cursor.fetchone()
        cursor.execute("SELECT id_dokter FROM dokter_rs_cabang WHERE id_dokter NOT LIKE %s",[id_dokter])
        arg2=cursor.fetchall()
        cursor.execute("SELECT kode_rs FROM dokter_rs_cabang WHERE kode_rs NOT IN(SELECT kode_rs FROM dokter_rs_cabang WHERE id_dokter=%s )",[id_dokter])
        arg3=cursor.fetchall()
        arguements={
            'current':arg,
            'alldoctors':arg2,
            'allcodes':arg3
        }
        return render(request,"UpdateDaftarDokter.html",arguements)
    else:
        return redirect('greenFeature:profile_page')


def updatelayananpoliklinik(request,id_poliklinik,kode_rs):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    cursor = connection.cursor()
    if request.method == 'POST':
        id_poliklinik1 = request.POST.get('id_poliklinik')
        print(id_poliklinik)
        nama = request.POST['nama_layanan']
        kode_rs_cabang1 = request.POST.get('kode_rs')
        deskripsi = request.POST['deskripsi']
        with transaction.atomic():
            try:
                cursor.execute("UPDATE layanan_poliklinik SET nama=%s,deskripsi=%s WHERE id_poliklinik=%s AND kode_rs_cabang=%s;",[nama,deskripsi,id_poliklinik,kode_rs])
                print(connection.queries)
                return redirect('purpleFeature:jadwalpoliklinik')
            except DatabaseError as Error:
                print(error)
    cursor.execute("SELECT * FROM layanan_poliklinik WHERE id_poliklinik=%s;",[id_poliklinik])
    poly=cursor.fetchone()

    args={
        'poliklinik':poly
    }

    if(role == 'admin'):
        return render(request,"FormUpdateLayananPoliklinik.html",args)
    else:
        return redirect('greenFeature:profile_page')


def deletelayananpoliklinik(request,id_poliklinik,kode_rs):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    cursor = connection.cursor()

    if(role == 'admin'):
        with transaction.atomic():
            try:
                cursor.execute("DELETE FROM layanan_poliklinik WHERE id_poliklinik=%s AND kode_rs_cabang=%s",[id_poliklinik,kode_rs])
                return redirect("purpleFeature:jadwalpoliklinik")
            except DatabaseError as Error:
                print(Error)


def deletejadwalpoliklinik(request,id_layanan):
    role=getPenggunaType(username)

    return render(request,"DaftarDokter.html")

def updatejadwalpoliklinik(request,id_jadwal_layanan_poliklinik):

purpleFeature/templates/navbar_admin.html
{% load static %}


<nav class="navbar navbar-expand-md navbar-light" style="background-color: #F3F9FF;height:17vh;">
	<a class="navbar-brand" href="{% url 'greenFeature:profile_page' %}"><img class="logo" src="{% static 'images/LOGO.svg' %}"></img></a>
	
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Sesi Konsultasi
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'redFeature:buat_sesikonsultasi' %}">Buat Sesi Konsultasi</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'redFeature:daftar_sesikonsultasi' %}">Daftar Sesi Konsultasi</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" style="color:#000000;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Poliklinik
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'purpleFeature:buatlayananpoliklinik' %}">Buat Layanan Poliklinik</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:jadwalpoliklinik' %}">Daftar Layanan Poliklinik</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:buatlayananpoliklinik' %}">Buat Jadwal Poliklinik</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:jadwalpoliklinik' %}">Daftar Jadwal Poliklinik</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					RS Cabang
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'redFeature:buat_rscabang' %}">Buat RS Cabang</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'redFeature:daftar_rscabang' %}">Daftar RS Cabang</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:daftardoktercabang' %}">Daftarkan Dokter</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:daftardokter' %}">Daftar Dokter RS Cabang</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" style="color:#000000;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Tindakan
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'greenFeature:buat_tindakan' %}">Buat Tindakan</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'greenFeature:daftar_tindakan' %}">Daftar Tindakan</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'greenFeature:buat_tindakan_poliklinik' %}">Buat Tindakan Poliklinik</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'greenFeature:daftar_tindakan_poliklinik' %}">Daftar Tindakan Poliklinik</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Resep & Obat 
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="#">Buat Resep</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Daftar Resep</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Buat Obat</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Daftar Obat</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Transaksi 
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'blueFeature:buatTransaksi'%}">Buat Transaksi</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'blueFeature:RUDadmin'%}">Daftar Transaksi</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<img src="{% static 'images/profile_icon.svg' %}" class="profile_icon"></img>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'greenFeature:profile_page' %}">Profil</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'firstFeature:homepage' %}">Log out</a>
				</div>
			</li>
			
		</ul>
	</div>
</nav>

purpleFeature/templates/navbar_pasien_dokter.html
{% load static %}

<body id="body_buat_tindakan">
	<nav class="navbar navbar-expand-md navbar-light" style="background-color: #F3F9FF;height:17vh;">
		<a class="navbar-brand" href="{% url 'greenFeature:profile_page' %}"><img class="logo" src="{% static 'images/LOGO.svg' %}"></img></a>
		
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav ml-auto"">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Sesi Konsultasi
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;"> 
						<a class="dropdown-item" href="{% url 'redFeature:daftar_sesikonsultasi' %}">Daftar Sesi Konsultasi</a>
					</div>
				</li>
				
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="color:#000000;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Poliklinik
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
						<a class="dropdown-item" href="{% url 'greenFeature:daftar_tindakan_poliklinik' %}">Daftar Tindakan Poliklinik</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'purpleFeature:jadwalpoliklinik' %}">Daftar Layanan Poliklinik</a>
					</div>
				</li>
				
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						RS Cabang
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
						<a class="dropdown-item" href="{% url 'redFeature:daftar_rscabang' %}">Daftar RS Cabang</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'purpleFeature:daftardokter' %}">Daftar Dokter RS Cabang</a>
					</div>
				</li>
				
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="color:#000000;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Tindakan
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;"> 
						<a class="dropdown-item" href="{% url 'greenFeature:daftar_tindakan' %}">Daftar Tindakan</a>
					</div>
				</li>
				
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Resep & Obat 
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
						<a class="dropdown-item" href="#">Daftar Resep</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#">Daftar Obat</a>
					</div>
				</li>
				
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Transaksi 
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
						<a class="dropdown-item" href="{% url 'blueFeature:RUDadmin'%}">Daftar Transaksi</a>
					</div>
				</li>
				
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<img src="{% static 'images/profile_icon.svg' %}" class="profile_icon"></img>
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
						<a class="dropdown-item" href="{% url 'greenFeature:profile_page' %}">Profil</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'firstFeature:homepage' %}">Log out</a>
					</div>
				</li>
				
			</ul>
		</div>
	</nav>