TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstFeature.urls')),
    path('', include('greenFeature.urls',namespace='greenFeature')),
    path('', include('purpleFeature.urls',namespace='purpleFeature')),
    path('', include('blueFeature.urls',namespace='blueFeature')),
    path('', include('sesikonsultasi.urls',namespace='redFeature')),
]

blueFeature/urls.py
from django.urls import path
from . import views

app_name = 'blueFeature'

urlpatterns = [
    path('buatTransaksi/', views.buatTransaksi, name='buatTransaksi'),
    
    path('RUDadmin/', views.rudAdmin, name='RUDadmin'),
    
    path('updateTransaksi/<id_transaksi>', views.updateTransaksi, name='updateTransaksi'),
    path('updateTransaksi/', views.updateTransaksi, name='updateTransaksi'),

    path('deleteTransaksi/<id_transaksi>', views.deleteTransaksi, name='deleteTransaksi'),
    path('deleteTransaksi/', views.deleteTransaksi, name='deleteTransaksi'),
]

firstFeature/urls.py
from django.urls import path
from . import views

app_name = 'firstFeature'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.loginPage, name='login_page'),
    path('register/', views.registerPage, name='register_page'),
    path('logout/', views.logout, name='logout'),
]

greenFeature/urls.py
from django.urls import path
from . import views

app_name = 'greenFeature'
urlpatterns = [
    path('profile/', views.profilePage, name='profile_page'),
    
    path('buat-tindakan/', views.buatTindakanPage, name='buat_tindakan'),
    
    path('daftar-tindakan/', views.daftarTindakanPage, name='daftar_tindakan'),
    
    path('update-tindakan/<id_konsultasi>/<no_urut>', views.updateTindakanPage, name='update_tindakan'),
    path('update-tindakan/', views.updateTindakanPage, name='update_tindakan'),
    
    path('buat-tindakan-poliklinik/', views.buatTindakanPoliklinikPage, name='buat_tindakan_poliklinik'),
    
    path('daftar-tindakan-poliklinik/', views.daftarTindakanPoliklinikPage, name='daftar_tindakan_poliklinik'),
    
    path('update-tindakan-poliklinik/<id_tindakan_poli>', views.updateTindakanPoliklinikPage, name='update_tindakan_poliklinik'),
    path('update-tindakan-poliklinik/', views.updateTindakanPoliklinikPage, name='update_tindakan_poliklinik'),
    
    path('delete-tindakan-poliklinik/<id_tindakan_poli>', views.deleteTindakanPoliklinikPage, name='delete_tindakan_poliklinik'),
    path('delete-tindakan-poliklinik/', views.deleteTindakanPoliklinikPage, name='delete_tindakan_poliklinik'),
    
    path('delete-tindakan/<id_konsultasi>/<no_urut>', views.deleteTindakanPage, name='delete_tindakan'),
    path('delete-tindakan/', views.deleteTindakanPage, name='delete_tindakan'),
]

purpleFeature/urls.py
from django.urls import path
from . import views

app_name = "purpleFeature"

urlpatterns = [
    path('daftardokter/',views.daftardokter,name = "daftardokter"),

    path('jadwal-poliklinik/',views.jadwalpoliklinik,name="jadwalpoliklinik"),

    path('jadwal-poliklinik-details/<id_poliklinik>',views.jadwalpoliklinikdetails,name = "jadwalpoliklinikdetails"),
    path('jadwal-poliklinik-details/',views.jadwalpoliklinikdetails,name = "jadwalpoliklinikdetails"),

    path('pembuatan-layanan-poliklinik/',views.buatlayananpoliklinik,name = "buatlayananpoliklinik"),

    path('update-daftar-dokter/<id_dokter>/<kode_rs>',views.updatedaftardokter,name = "updatedaftardokter"),
    path('update-daftar-dokter/',views.updatedaftardokter,name="updatedaftardokter"),

    path('daftar-dokter-rs-cabang/',views.daftardoktercabang,name = "daftardoktercabang"),

    path('update-layanan-poliklinik/<id_poliklinik>/<kode_rs>',views.updatelayananpoliklinik,name = "updatelayananpoliklinik"),
    path('update-layanan-poliklinik/',views.updatelayananpoliklinik,name = "updatelayananpoliklinik"),

    path('update-jadwal-poliklinik/<id_jadwal_layanan_poliklinik>',views.updatejadwalpoliklinik,name = "updatejadwalpoliklinik"),
    path('update-jadwal-poliklinik/',views.updatejadwalpoliklinik,name = "updatejadwalpoliklinik"),

    path('delete-layanan-poliklinik/<id_poliklinik>/<kode_rs>',views.deletelayananpoliklinik,name="deletelayananpoliklinik"),
    path('delete-layanan-poliklinik',views.deletelayananpoliklinik,name="deletelayananpoliklinik"),

    path('delete-jadwal-poliklinik/<id_poliklinik>/<id_layanan>',views.deletejadwalpoliklinik,name="deletejadwalpoliklinik"),
    path('delete-jadwal-poliklinik/',views.deletejadwalpoliklinik,name="deletejadwalpoliklinik"),

    path('delete-dokter/<id_dokter>/<kode_rs>',views.deletedokter,name="deletedokter"),
    path('delete-dokter/',views.deletedokter,name="deletedokter")
]

sesikonsultasi/urls.py
from django.urls import path
from . import views

app_name = 'sesikonsultasi'

urlpatterns = [
    path('buat-sesikonsultasi/', views.buatSesiPage, name='buat_sesikonsultasi'),

    path('daftar-sesikonsultasi/', views.daftarSesiPage, name='daftar_sesikonsultasi'),

    path('update-sesikonsultasi/<id_konsultasi>/<no_rekam_medis>/', views.updateSesiPage, name='update_sesikonsultasi'),
    path('update-sesikonsultasi/', views.updateSesiPage, name='update_sesikonsultasi'),

    path('buat-rscabang/', views.buatRscabangPage, name='buat_rscabang'),

    path('daftar-rscabang/', views.daftarRscabangPage, name='daftar_rscabang'),
    
    path('update-rscabang/<kode_rs>', views.updateRscabangPage, name='update_rscabang'),
    path('update-rscabang/', views.updateRscabangPage, name='update_rscabang'),

    path('delete-sesikonsultasi/<id_konsultasi>/<no_rekam_medis>', views.deleteSesiPage, name='delete_sesikonsultasi'),
    path('delete-sesikonsultasi/', views.deleteSesiPage, name='delete_sesikonsultasi'),

    path('delete-rscabang/<kode_rs>', views.deleteRscabangPage, name='delete_rscabang'),
    path('delete-rscabang/', views.deleteRscabangPage, name='delete_rscabang'),
    # dilanjutkan ...
]

sesikonsultasi/models.py
from django.db import models

# Create your models here.

sesikonsultasi/views.py
from django.db import connection, DatabaseError, transaction
from django.shortcuts import render, redirect

def buatSesiPage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        cursor.execute('SELECT no_rekam_medis FROM pasien')
        no_rekam_medis_all = cursor.fetchall()
        cursor.execute('SELECT id_transaksi FROM transaksi')
        id_transaksi_all = cursor.fetchall()
    if request.method == 'POST':
        no_rekam_medis = request.POST["no_rekam_medis"]
        tanggal = request.POST["tanggal"]
        id_transaksi = request.POST["id_transaksi"]
        id_konsultasi = generateIdKonsultasi()
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                        cursor.execute('INSERT INTO sesi_konsultasi VALUES (%s, %s, %s, %s, %s, %s)', [id_konsultasi, no_rekam_medis, tanggal, 0, "booked", id_transaksi])
            return redirect('redFeature:daftar_sesikonsultasi')
        except DatabaseError as e:
            print("error")
            return render(request, "buatsesikonsultasi_admin.html", {'id_transaksi_all':id_transaksi_all, 'no_rekam_medis_all':no_rekam_medis_all})
    else:
        if (role == "admin"):
            return render(request, 'buatsesikonsultasi_admin.html', {'id_transaksi_all':id_transaksi_all, 'no_rekam_medis_all':no_rekam_medis_all})
        else:
            return redirect('greenFeature:profile_page')


def buatRscabangPage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    if request.method == 'POST':
        kode_rs = request.POST["kode_rs"]
        nama = request.POST["nama"]
        tanggal = request.POST["tanggal"]
        jalan = request.POST["jalan"]
        nomor = request.POST["nomor"]
        kota = request.POST["kota"]
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('INSERT INTO rs_cabang VALUES (%s, %s, %s, %s, %s, %s)', [kode_rs, nama, tanggal, jalan, nomor, kota])
            return redirect('redFeature:daftar_rscabang')        
        except DatabaseError as e:
            return render(request, 'buatrscabang.html')
    else:
        if(role == "admin"):
            return render(request, 'buatrscabang.html')
        else:
            return redirect('greenFeature:profile_page')
        


def daftarSesiPage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        daftar_sesi_konsultasi = []
        cursor.execute('SELECT * FROM sesi_konsultasi')
        sesi_konsultasi_all = cursor.fetchall()
        for sesi_konsultasi in sesi_konsultasi_all:
            cursor.execute('SELECT id_konsultasi FROM sesi_konsultasi')
            id_konsultasi_all = cursor.fetchall()
            sesi = [id_konsultasi[0] for id_konsultasi in id_konsultasi_all]
            daftar_sesi_konsultasi.append(sesi)
    mylist = zip(daftar_sesi_konsultasi, sesi_konsultasi_all)
    if (role == "admin"):
        return render(request, 'daftarsesikonsultasi_admin.html', {'mylist':mylist})
    else:
        return render(request, 'daftarsesikonsultasi_nonadmin.html', {'mylist':mylist})


def daftarRscabangPage(request):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        daftar_rs_cabang = []
        cursor.execute('SELECT * FROM rs_cabang')
        rs_cabang_all = cursor.fetchall()
        for rs_cabang in rs_cabang_all:
            cursor.execute('SELECT kode_rs FROM rs_cabang')
            kode_rs_all = cursor.fetchall()
            rs = [kode_rs[0] for kode_rs in kode_rs_all]
            daftar_rs_cabang.append(rs)
    mylist = zip(daftar_rs_cabang, rs_cabang_all)
    if(role == "admin"):
        return render(request, 'daftarrscabang_admin.html', {'mylist':mylist})
    else:
        return render(request, 'daftarrscabang_nonadmin.html', {'mylist':mylist})



def updateSesiPage(request, id_konsultasi, no_rekam_medis):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM sesi_konsultasi WHERE id_konsultasi = %s AND no_rekam_medis_pasien = %s',[id_konsultasi, no_rekam_medis])
        sesi_konsultasi = cursor.fetchone()
        cursor.execute('SELECT id_konsultasi FROM sesi_konsultasi WHERE id_konsultasi = %s AND no_rekam_medis_pasien = %s',[id_konsultasi, no_rekam_medis])
        id_konsultasi_all = cursor.fetchall()
    if request.method == 'POST':
        tanggal = request.POST["tanggal"]
        status = request.POST["status"]
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    print("masok")
                    print(status)
                    cursor.execute('UPDATE sesi_konsultasi SET tanggal = %s, status = %s WHERE id_konsultasi = %s' , [tanggal, status, id_konsultasi])
            return redirect('redFeature:daftar_sesikonsultasi')
        except DatabaseError as e:
            print("error")
            return render(request, 'updatesesikonsultasi.html', {'sesi_konsultasi':sesi_konsultasi, 'id_konsultasi_all':id_konsultasi_all})    
    else:
        if(role == "admin" and sesi_konsultasi):
            return render(request, 'updatesesikonsultasi.html', {'sesi_konsultasi':sesi_konsultasi, 'id_konsultasi_all':id_konsultasi_all})    
        else:
            return redirect('greenFeature:profile_page')   

def updateRscabangPage(request, kode_rs):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    with connection.cursor() as cursor:
        cursor.execute('SELECT * FROM rs_cabang WHERE kode_rs = %s',[kode_rs])
        rs_cabang = cursor.fetchone()
    if request.method == 'POST':
        nama = request.POST["nama"]
        tanggal = request.POST["tanggal"]
        jalan = request.POST["jalan"]
        kota = request.POST["kota"]
        nomor = request.POST["nomor"]
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('UPDATE rs_cabang SET nama = %s, tanggal_pendirian = %s, jalan = %s, kota= %s, nomor= %s', [nama, tanggal, jalan, kota, nomor])
            return redirect('redFeature:daftar_rscabang')
        except DatabaseError as e:
            return render(request, 'updaterscabang.html', {'rs_cabang': rs_cabang})
    else:
        if(role == "admin" and rs_cabang):
            return render(request, 'updaterscabang.html', {'rs_cabang': rs_cabang})
        else:
            return redirect('greenFeature:profile_page')

def deleteSesiPage(request, id_konsultasi, no_rekam_medis):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    if(role == "admin"):
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('DELETE FROM sesi_konsultasi WHERE id_konsultasi = %s AND no_rekam_medis_pasien = %s',[id_konsultasi, no_rekam_medis])
        except DatabaseError as e:
             return redirect('redFeature:daftar_sesikonsultasi')
    return redirect('redFeature:daftar_sesikonsultasi')

def deleteRscabangPage(request, kode_rs):
    if 'Username' not in request.session:
        return redirect("firstFeature:login_page")
    else:
        role = request.session['Role']
        username = request.session['Username']
    if(role == "admin"):
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    cursor.execute('DELETE FROM rs_cabang WHERE kode_rs = %s',[kode_rs])
        except DatabaseError as e:
             return redirect('redFeature:daftar_rscabang')
    return redirect('redFeature:daftar_rscabang')

def generateIdKonsultasi():
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_konsultasi FROM sesi_konsultasi ORDER BY RIGHT(id_konsultasi, -2)::int DESC")
        sesi_konsultasi = cursor.fetchone()
        print(sesi_konsultasi)
        if(sesi_konsultasi):
            id_dokter = sesi_konsultasi[0]
            print(id_dokter)
            new_number = int(id_dokter[2::])+1
            print(new_number)
            return "SK"+str(new_number)
        return "SK1"
            

sesikonsultasi/templates/daftarrscabang_admin.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-edge">
		<title>Daftar RS Cabang</title>
		<meta name="description" content="">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'stylebuatsesi.css' %}">
  
</head>

<body>
{% include 'navbar_admin_naura.html' %}
<h3 id="formtitle">Daftar RS Cabang</h3>

<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<div id="listspace" style="background-color:white">
			<div class="table-responsive">   
			<table class="table table-borderless">
			  <thead>
				<tr>
				  <th scope="col" id="field">Kode RS</th>
				  <th scope="col" id="field">Nama</th>
				  <th scope="col" id="field">Tanggal Pendirian</th>
				  <th scope="col" id="field">Jalan</th>
				  <th scope="col" id="field">Kota</th>
				  <th scope="col" id="field">Nomor</th>
				</tr>
			  </thead>
			  <tbody>
			  	{% for daftar_rs_cabang, rs_cabang in mylist %}
				<tr>
				  <th scope="row">{{rs_cabang.0}}</th>
				  <td>{{rs_cabang.1}}</td>
				  <td>{{rs_cabang.2}}</td>
				  <td>{{rs_cabang.3}}</td>
				  <td>{{rs_cabang.4}}</td>
				  <td>{{rs_cabang.5}}</td>
				  <td>
					<button type="submit" class="button_update" scope="col"><a style = "text-decoration:none; color: #3750B2;" href="{% url 'redFeature:update_rscabang' %}{{rs_cabang.0}}">Update</a></button>
					<button type="submit" class="button_delete" scope="col"><a style = "text-decoration:none; color: white;" href="{% url 'redFeature:delete_rscabang' %}{{rs_cabang.0}}">Delete</a></button>
				  </td>
				</tr>
				{% endfor %}
			  </tbody>
			</table>
		</div>
	</div>
		
	<div class="col-sm-2"></div>
</div>

sesikonsultasi/templates/daftarrscabang_nonadmin.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-edge">
		<title>Daftar RS Cabang</title>
		<meta name="description" content="">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'stylebuatsesi.css' %}">
</head>

<body>
{% include 'navbar_nonadmin.html' %}
<h3 id="formtitle">Daftar RS Cabang</h3>

<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<div id="listspace" style="background-color:white">
			<div class="table-responsive">   
			<table class="table table-borderless">
			  <thead>
				<tr>
				  <th scope="col" id="field">Kode RS</th>
				  <th scope="col" id="field">Nama</th>
				  <th scope="col" id="field">Tanggal Pendirian</th>
				  <th scope="col" id="field">Jalan</th>
				  <th scope="col" id="field">Kota</th>
				  <th scope="col" id="field">Nomor</th>
				</tr>
			  </thead>
			  <tbody>
			  	{% for daftar_rs_cabang, rs_cabang in mylist %}
				<tr>
				  <th scope="row">{{rs_cabang.0}}</th>
				  <td>{{rs_cabang.1}}</td>
				  <td>{{rs_cabang.2}}</td>
				  <td>{{rs_cabang.3}}</td>
				  <td>{{rs_cabang.4}}</td>
				  <td>{{rs_cabang.5}}</td>
				</tr>
				{% endfor %}
			  </tbody>
			</table>
		</div>
	</div>
		
	<div class="col-sm-2"></div>
</div>

sesikonsultasi/templates/navbar_admin_naura.html
<!DOCTYPE html>
{% load static %}
<html>
<body>
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #F3F9FF;height:17vh;">
	<a class="navbar-brand" href="{% url 'greenFeature:profile_page' %}"><img class="logo" style = "width: 27vw;height: 8vh;" src="{% static 'images/LOGO.svg' %}"></img></a>
	
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav ml-auto"">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="naura" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Sesi Konsultasi
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'redFeature:buat_sesikonsultasi' %}">Buat Sesi Konsultasi</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'redFeature:daftar_sesikonsultasi' %}">Daftar Sesi Konsultasi</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" style="color:#000000;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Poliklinik
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'purpleFeature:buatlayananpoliklinik' %}">Buat Layanan Poliklinik</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:jadwalpoliklinik' %}">Daftar Layanan Poliklinik</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:buatlayananpoliklinik' %}">Buat Jadwal Poliklinik</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:jadwalpoliklinik' %}">Daftar Jadwal Poliklinik</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					RS Cabang
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'redFeature:buat_rscabang' %}">Buat RS Cabang</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'redFeature:daftar_rscabang' %}">Daftar RS Cabang</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:daftardoktercabang' %}">Daftarkan Dokter</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'purpleFeature:daftardokter' %}">Daftar Dokter RS Cabang</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" style="color:#000000;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Tindakan
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'greenFeature:buat_tindakan' %}">Buat Tindakan</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'greenFeature:daftar_tindakan' %}">Daftar Tindakan</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'greenFeature:buat_tindakan_poliklinik' %}">Buat Tindakan Poliklinik</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'greenFeature:daftar_tindakan_poliklinik' %}">Daftar Tindakan Poliklinik</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Resep & Obat 
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="#">Buat Resep</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Daftar Resep</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Buat Obat</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Daftar Obat</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Transaksi 
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'blueFeature:buatTransaksi'%}">Buat Transaksi</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'blueFeature:RUDadmin'%}">Daftar Transaksi</a>
				</div>
			</li>
			
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" style="color:#000000;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<img src="{% static 'images/profile_icon.svg' %}" class="profile_icon"></img>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="background-color:#EDF1FF;border:0px;">
					<a class="dropdown-item" href="{% url 'greenFeature:profile_page' %}">Profil</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'firstFeature:logout' %}">Log out</a>
				</div>
			</li>
			
		</ul>
	</div>
</nav>